import { Inter } from 'next/font/google'
import './globals.scss'
import SideBar from '@/Components/Sidebar'
import MenuManager from '@/Components/Menu/MenuManager'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={inter.className}>
        <MenuManager>
        <SideBar/>
        <div className='main-container' id='main-container'>
        {children}
        </div>
        </MenuManager>
        </body>
    </html>
  )
}
